---
title: "MarketBasketAnalysisWith_R"
output: pdf_document
date: "`r Sys.Date()`"
---

```{r}
#load the required libraries
library(arules)
library(arulesViz)
#load the data
data("Income")
#inspect the data
str(Income)
inspect(Income)
```

```{r}
#Use the apriori algorithm to mine association rules
income_rules <- apriori(Income, parameter = list(support = 0.5, confidence = 0.5))
```

```{r}
# support 0.1 and confidence0.8 
#At least 10% of the transactions should contain the items in the rule
#At least 80% of the transactions containing the antecedent should also contain the consequent

income_rules <- apriori(Income, parameter = list(support = 0.1, confidence = 0.8))

```
Explaining the parameters: 
```{r}
#Inspect and analyze the generated rules.
inspect(income_rules)


```



```{r}
#Sort the rules based on support, confidence, and lift
income_rules <- sort(income_rules, by = "lift")
inspect(income_rules)


```

```{r}
#sort the rules based on confidence
income_rules <- sort(income_rules, by = "confidence")
inspect(income_rules)
```

```{r}
#sort the rules based on support
income_rules <- sort(income_rules, by = "support")
inspect(income_rules)
```

```{r}
#Identify and remove redundant rules.
income_rules <- income_rules[!duplicated(income_rules)]
```


```{r}
#Visualize the association rules using plot function and ensure interactivity
plot(income_rules, method = "graph", control = list(type = "items"))
```

